name: Python applicationtest

on:
  workflow_dispatch:

  env:
    PYTHON_VERSION: 3.8
    DEPENDENCY_FILE: requirements.txt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f ${{ env.DEPENDENCY_FILE }} ]; then
          python -m pip install -r ${{ env.DEPENDENCY_FILE }}
        fi

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: 'true'
        environment: 'azurecloud'
        allow-no-subscriptions: 'false'
        audience: 'api://AzureADTokenExchange'
        auth-type: 'SERVICE_PRINCIPAL'

    - name: Deploy to Azure Web App
      uses: Azure/webapps-deploy@v3.0.1
      with:
        app-name: 'twactionsapp1'
        slot-name: 'production'
        package: '.'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
